# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0b61fbdc96b59952b94955627581e5892fb8a75993980c37695efb4dfdc42b9852a9fdc14ed60effd1ebff05561482881f4ae1e0680e8007ce583311addb78d

test:
  secret_key_base: 87bec7fac2f270524094fbe92d004faa3a482430e6609b608842db48579b6d00b165d45e161541e7cc1172b164ce2a36e81aa47674210fa2bd54a9a3b63593d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
